services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"  # Mapping MySQL container port to host
    volumes:
      - /media/twelvetb/services/lib/mysql:/var/lib/mysql
      - pipeline-docker-compose/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: