services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3308:3306"  # Mapping MySQL container port to host
    volumes:
      - ~/docker/mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./tables/datastore.sql:/docker-entrypoint-initdb.d/datastore.sql
      - ./tables/files.sql:/docker-entrypoint-initdb.d/files.sql
      - ./tables/users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./tables/project.sql:/docker-entrypoint-initdb.d/project.sql
      - ./tables/team.sql:/docker-entrypoint-initdb.d/team.sql
      - ./tables/aolme_videos.sql:/docker-entrypoint-initdb.d/aolme_videos.sql

  dao-service:
    build:
      context: ./dao-service  # Ensure Docker uses the right build context
      dockerfile: Dockerfile  # Explicitly mention Dockerfile, just in case it's named Dockerfile
    container_name: dao_service
    ports:
      - "5010:5010"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_DATABASE=app_db
      - FLASK_APP=app.py  # Ensure Flask knows where to find app.py
      - FLASK_ENV=development
    env_file:
      - ./dao-service/.env  # Load environment variables from .env file
    depends_on:
      - mysql
    volumes:
      - ./dao-service:/app  # Ensure the app files are copied to the correct location
    command: flask run --host=0.0.0.0 --port=5010  # Start the Flask app

volumes:
  mysql_data:
