services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"  # Mapping MySQL container port to host
    volumes:
      - /media/twelvetb/services/lib/mysql:/var/lib/mysql
      - ./pipeline-docker-compose/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./pipeline-docker-compose/tables/datastore.sql:/docker-entrypoint-initdb.d/datastore.sql

  dao-service:
    build:
      context: ./dao-service
    container_name: dao_service
    ports:
      - "5010:5010"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_DATABASE=app_db
      - FLASK_APP=app.py
      - FLASK_ENV=development
    network_mode: "host"
    depends_on:
      - mysql
    volumes:
      - ./dao-service/data:/app
    command: flask run --host=0.0.0.0 --port=5010

volumes:
  mysql_data: